name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: "The semver to use"
        required: true
        default: "patch"
        type: choice
        options:
          - auto
          - patch
          - minor
          - major
      baseTag:
        description: 'base release tag'
  pull_request:
    types: [closed]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: "0"
      - uses: actions/setup-node@v3
      - run: npm i

      - uses: sameer-coder/optic-release-automation-action@main
        with:
          github-token: ${{ github.token }}
          semver: ${{ github.event.inputs.semver }}
          base-tag: ${{ github.event.inputs.baseTag }}
